### ISSUE TITLE
Fixes for Netflix Subtitle Downloader 0.13.10

### ISSUE THREAD

**Issue by essam315** [Zarxrax/NetflixSubs#2]
Hi, thank you for your great work with Netflix Subtitle Downloader, in the current release you forgot to
modify MSL.py to download the subtitles of Arabic and Greek in SRT format by changing it from

                # Subtiltes
                # 'dfxp-ls-sdh',
                'simplesdh',
                # 'nflx-cmisc',

to

               # Subtiltes
                # 'dfxp-ls-sdh',
                # 'simplesdh',
                'webvtt-lssdh-ios8',
                # 'nflx-cmisc',

and in KodiHelper.py changing from

        is_helper = inputstreamhelper.Helper('mpd', drm='widevine')
        if not is_helper.check_inputstream():
            return False

to

        is_helper = inputstreamhelper.Helper('mpd', drm='widevine')
        # if not is_helper.check_inputstream():
        #    return False

will prevent the plugin from asking for installing widevine and from playing the videos

and in NetflixSession.py changing 

`def fetch_episodes_by_season(self, season_id, list_from=-1, list_to=40):`

to

`def fetch_episodes_by_season(self, season_id, list_from=-1, list_to=99):`

should fix a problem with Japanese series with episodes more than 40

and this is  0.13.10.8 with the fixes.

Thank you again for your great work.

https://mega.nz/#!Nw8E1a5J!iJ3EGu9ApmQ7rWb_Fa35pAUujfkRPQz7_i9X6rE188w

**Comment by Zarxrax** [comment]
As for disabling widevine so that videos don't play, is there any good reason for this? Does this help make it easier or faster to download subtitles?

**Comment by Zarxrax** [comment]
Ok I will try to investigate that when I get some time.

**Comment by essam315** [comment]
Thank you so much.

**Comment by essam315** [comment]
When i try to download the Arabic subtitles using "NetflixSubs-0.13.10-revision1" and write "ar" in "only download subtitles with this language" i only get the "Subtitle_urls" file, but if i left "only download subtitles with this language" empty, i download the subtitles with all the other available languages and the Arabic subtitles.

Using this modified MSL.py fixes the problem.

https://mega.nz/#!dps3CYZR!g0ymshFrbuY4OLcFf8pSY0gp7DrhbgS5_HTm0l-vx7E

**Comment by essam315** [comment]
Removing "lower" from MSL.py was the fix

if (filename_lang == self.nx_common.get_setting('subtitle_language').lower) or (self.nx_common.get_setting('subtitle_language') == ''):
                    filename_title = xbmc.getInfoLabel('VideoPlayer.TVShowTitle')

**Comment by m7mdibrahimo** [comment]
I can not find an inputstream option
