### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by drewm89** [Zarxrax/NetflixSubs#5]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X ] Are you running the latest version?

### Description

I get an error message when I attempt to access a Netflix profile

### Steps to Reproduce

1. Click on Netlix Subs
2. Click on Profile Name

**Expected behavior:** I expect to be taken to the list of Netflix folder

**Actual behavior:** Error message

## Context (Environment)

Please see the attached error log

* [X] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

[kodi.log](https://github.com/Zarxrax/NetflixSubs/files/3311456/kodi.log)

**Comment by edoreld** [comment]
I'm having exactly the same issue with the latest v18 build from Kodi.

**Comment by Zarxrax** [comment]
Netflix changed something on their end. This software will no longer be updated. I recommend the following software if you want to download subtitles: https://chrome.google.com/webstore/detail/subadub/jamiekdimmhnnemaaimmdahnahfmfdfk?hl=en-US
